services:
  helm-kubectl-openjdk21-jre:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DTZAR_HELM_KUBECTL_VERSION: ${DTZAR_HELM_KUBECTL_VERSION}
      tags:
      - ghcr.io/bluestep-systems/helm-kubectl-openjdk21-jre:latest
      - ghcr.io/bluestep-systems/helm-kubectl-openjdk21-jre:1.0.0
    image: hcr.io/bluestep-systems/helm-kubectl-openjdk21-jre
